# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/Cengine/Cengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/Cengine/Cengine/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Cengine/Cengine/build/CMakeFiles /home/runner/work/Cengine/Cengine/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Cengine/Cengine/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named index

# Build rule for target.
index: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 index
.PHONY : index

# fast build rule for target.
index/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/build
.PHONY : index/fast

src/colorFramebuffer.o: src/colorFramebuffer.cpp.o
.PHONY : src/colorFramebuffer.o

# target to build an object file
src/colorFramebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/colorFramebuffer.cpp.o
.PHONY : src/colorFramebuffer.cpp.o

src/colorFramebuffer.i: src/colorFramebuffer.cpp.i
.PHONY : src/colorFramebuffer.i

# target to preprocess a source file
src/colorFramebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/colorFramebuffer.cpp.i
.PHONY : src/colorFramebuffer.cpp.i

src/colorFramebuffer.s: src/colorFramebuffer.cpp.s
.PHONY : src/colorFramebuffer.s

# target to generate assembly for a file
src/colorFramebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/colorFramebuffer.cpp.s
.PHONY : src/colorFramebuffer.cpp.s

src/fullscreenQuad.o: src/fullscreenQuad.cpp.o
.PHONY : src/fullscreenQuad.o

# target to build an object file
src/fullscreenQuad.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/fullscreenQuad.cpp.o
.PHONY : src/fullscreenQuad.cpp.o

src/fullscreenQuad.i: src/fullscreenQuad.cpp.i
.PHONY : src/fullscreenQuad.i

# target to preprocess a source file
src/fullscreenQuad.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/fullscreenQuad.cpp.i
.PHONY : src/fullscreenQuad.cpp.i

src/fullscreenQuad.s: src/fullscreenQuad.cpp.s
.PHONY : src/fullscreenQuad.s

# target to generate assembly for a file
src/fullscreenQuad.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/fullscreenQuad.cpp.s
.PHONY : src/fullscreenQuad.cpp.s

src/instancedMesh.o: src/instancedMesh.cpp.o
.PHONY : src/instancedMesh.o

# target to build an object file
src/instancedMesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/instancedMesh.cpp.o
.PHONY : src/instancedMesh.cpp.o

src/instancedMesh.i: src/instancedMesh.cpp.i
.PHONY : src/instancedMesh.i

# target to preprocess a source file
src/instancedMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/instancedMesh.cpp.i
.PHONY : src/instancedMesh.cpp.i

src/instancedMesh.s: src/instancedMesh.cpp.s
.PHONY : src/instancedMesh.s

# target to generate assembly for a file
src/instancedMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/instancedMesh.cpp.s
.PHONY : src/instancedMesh.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/meshImporter.o: src/meshImporter.cpp.o
.PHONY : src/meshImporter.o

# target to build an object file
src/meshImporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/meshImporter.cpp.o
.PHONY : src/meshImporter.cpp.o

src/meshImporter.i: src/meshImporter.cpp.i
.PHONY : src/meshImporter.i

# target to preprocess a source file
src/meshImporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/meshImporter.cpp.i
.PHONY : src/meshImporter.cpp.i

src/meshImporter.s: src/meshImporter.cpp.s
.PHONY : src/meshImporter.s

# target to generate assembly for a file
src/meshImporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/meshImporter.cpp.s
.PHONY : src/meshImporter.cpp.s

src/plane.o: src/plane.cpp.o
.PHONY : src/plane.o

# target to build an object file
src/plane.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/plane.cpp.o
.PHONY : src/plane.cpp.o

src/plane.i: src/plane.cpp.i
.PHONY : src/plane.i

# target to preprocess a source file
src/plane.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/plane.cpp.i
.PHONY : src/plane.cpp.i

src/plane.s: src/plane.cpp.s
.PHONY : src/plane.s

# target to generate assembly for a file
src/plane.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/plane.cpp.s
.PHONY : src/plane.cpp.s

src/renderer.o: src/renderer.cpp.o
.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i
.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s
.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/sceneNode.o: src/sceneNode.cpp.o
.PHONY : src/sceneNode.o

# target to build an object file
src/sceneNode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/sceneNode.cpp.o
.PHONY : src/sceneNode.cpp.o

src/sceneNode.i: src/sceneNode.cpp.i
.PHONY : src/sceneNode.i

# target to preprocess a source file
src/sceneNode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/sceneNode.cpp.i
.PHONY : src/sceneNode.cpp.i

src/sceneNode.s: src/sceneNode.cpp.s
.PHONY : src/sceneNode.s

# target to generate assembly for a file
src/sceneNode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/sceneNode.cpp.s
.PHONY : src/sceneNode.cpp.s

src/shadowFramebuffer.o: src/shadowFramebuffer.cpp.o
.PHONY : src/shadowFramebuffer.o

# target to build an object file
src/shadowFramebuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/shadowFramebuffer.cpp.o
.PHONY : src/shadowFramebuffer.cpp.o

src/shadowFramebuffer.i: src/shadowFramebuffer.cpp.i
.PHONY : src/shadowFramebuffer.i

# target to preprocess a source file
src/shadowFramebuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/shadowFramebuffer.cpp.i
.PHONY : src/shadowFramebuffer.cpp.i

src/shadowFramebuffer.s: src/shadowFramebuffer.cpp.s
.PHONY : src/shadowFramebuffer.s

# target to generate assembly for a file
src/shadowFramebuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/shadowFramebuffer.cpp.s
.PHONY : src/shadowFramebuffer.cpp.s

src/skybox.o: src/skybox.cpp.o
.PHONY : src/skybox.o

# target to build an object file
src/skybox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/skybox.cpp.o
.PHONY : src/skybox.cpp.o

src/skybox.i: src/skybox.cpp.i
.PHONY : src/skybox.i

# target to preprocess a source file
src/skybox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/skybox.cpp.i
.PHONY : src/skybox.cpp.i

src/skybox.s: src/skybox.cpp.s
.PHONY : src/skybox.s

# target to generate assembly for a file
src/skybox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/index.dir/build.make CMakeFiles/index.dir/src/skybox.cpp.s
.PHONY : src/skybox.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... index"
	@echo "... src/colorFramebuffer.o"
	@echo "... src/colorFramebuffer.i"
	@echo "... src/colorFramebuffer.s"
	@echo "... src/fullscreenQuad.o"
	@echo "... src/fullscreenQuad.i"
	@echo "... src/fullscreenQuad.s"
	@echo "... src/instancedMesh.o"
	@echo "... src/instancedMesh.i"
	@echo "... src/instancedMesh.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/meshImporter.o"
	@echo "... src/meshImporter.i"
	@echo "... src/meshImporter.s"
	@echo "... src/plane.o"
	@echo "... src/plane.i"
	@echo "... src/plane.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/sceneNode.o"
	@echo "... src/sceneNode.i"
	@echo "... src/sceneNode.s"
	@echo "... src/shadowFramebuffer.o"
	@echo "... src/shadowFramebuffer.i"
	@echo "... src/shadowFramebuffer.s"
	@echo "... src/skybox.o"
	@echo "... src/skybox.i"
	@echo "... src/skybox.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

